### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by kien5436** [kien5436/vue-nav-tab#1]
- [x] Cross browser scrollbar for long tabslist
- [ ] Tab leave confirm
- [x] Tab changes events: active, inactive or closed
- [x] Drag n drop
- [x] i18n
- [x] Open, close tabs
- [x] Refresh tabs
- [x] Do operation via context menu
